### ISSUE TITLE
Missing import statements?

### ISSUE THREAD

**Issue by JoshMcCullough** [crissdev/bootstrap-scss#4]
Shouldn't each SCSS file stand on its own? E.g. if you look at `_variables.scss`, it references things in `_functions.scss`, etc. I believe these local imports should be at the top of the file otherwise the consumer needs to import all of the referenced SCSS files in the proper order.

If I am consuming some Bootstrap SCSS, and I need to access the variable `$spacer`, I would write my SCSS as follows:

```scss
@import "~bootstrap-scss/_variables";

.my-class {
  margin-top: $spacer * 2;
}
```

But this will fail to compile with the message: 

>argument `$color` of `darken($color, $amount)` must be a color

But I'm not doing _anything_ with color here. This is because of the line `$link-hover-color:          darken($link-color, 15%) !default;` in `_variables.scss` -- that line references `$link-color` which in turn references the `theme-color` function in `_functions.scss`.

In order to get my SCSS to compile, I need to dig into `_variables.scss` and determine which files it needs to import, and then do the same task again for each of those files, and add them all as imports to my SCSS:

```scss
@import '~bootstrap-scss/_functions';
@import '~bootstrap-scss/_mixins';
@import '~bootstrap-scss/_variables';

.my-class {
  margin-top: $spacer * 2;
}
```

IMO, `_variables.scss` should look like this at the top...

```scss
@import '_functions';
@import '_mixins';
```

...and all of the other SCSS files should import what they need as well. In the end, I should be able to pick any single SCSS file and compile it on its own.
